title: Portfolio 
description: Keep an eye on updates!
theme: jekyll-theme-minimal
url: "https://jkhadgi.github.io"
baseurl: ""  # leave empty for root site
author: "Jasmita Khadgi"       

# Pages to show in header navigation
header_pages:
  - index.md
  - about.md
 
