title: Jasmita's homepage
description: Bookmark this to keep an eye on my project updates!
theme: jekyll-theme-minimal
url: "https://jkhadgi.github.io"
baseurl: ""  # leave empty for root site
author: "Jasmita Khadgi"

# Pages to show in header navigation
header_pages:
  - index.md
  - about.md

