title: Portfolio


theme: jekyll-theme-minimal
url: "https://jkhadgi.github.io"
baseurl: ""  # leave empty for root site
author: "Jasmita Khadgi"

# Pages to show in header navigation
header_pages:
  - index.md
  - presentations.md
  - about.md
  
